In [1]:
import pandas as pd

df = pd.read_csv('./data/stock-data.csv')

print(df.head())
print('\n')
print(df.info())

         Date  Close  Start   High    Low  Volume
0  2018-07-02  10100  10850  10900  10000  137977
1  2018-06-29  10700  10550  10900   9990  170253
2  2018-06-28  10400  10900  10950  10150  155769
3  2018-06-27  10900  10800  11050  10500  133548
4  2018-06-26  10800  10900  11000  10700   63039


<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    20 non-null     str
 1   Close   20 non-null     int64
 2   Start   20 non-null     int64
 3   High    20 non-null     int64
 4   Low     20 non-null     int64
 5   Volume  20 non-null     int64
dtypes: int64(5), str(1)
memory usage: 1.1 KB
None

In [2]:
df['new_Date'] = pd.to_datetime(df['Date'])

print(df.head())
print('\n')
print(df.info())
print('\n')
print(type(df['new_Date'][0]))

         Date  Close  Start   High    Low  Volume   new_Date
0  2018-07-02  10100  10850  10900  10000  137977 2018-07-02
1  2018-06-29  10700  10550  10900   9990  170253 2018-06-29
2  2018-06-28  10400  10900  10950  10150  155769 2018-06-28
3  2018-06-27  10900  10800  11050  10500  133548 2018-06-27
4  2018-06-26  10800  10900  11000  10700   63039 2018-06-26


<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      20 non-null     str
 1   Close     20 non-null     int64
 2   Start     20 non-null     int64
 3   High      20 non-null     int64
 4   Low       20 non-null     int64
 5   Volume    20 non-null     int64
 6   new_Date  20 non-null     datetime64[us]
dtypes: datetime64[us](1), int64(5), str(1)
memory usage: 1.2 KB
None


<class 'pandas.Timestamp'>

In [3]:
# 문자열을 timestamp로 변환


df = df.set_index('new_Date')
df = df.drop('Date', axis=1)

print(df.head())
print('\n')
print(df.info())

            Close  Start   High    Low  Volume
new_Date
2018-07-02  10100  10850  10900  10000  137977
2018-06-29  10700  10550  10900   9990  170253
2018-06-28  10400  10900  10950  10150  155769
2018-06-27  10900  10800  11050  10500  133548
2018-06-26  10800  10900  11000  10700   63039


<class 'pandas.DataFrame'>
DatetimeIndex: 20 entries, 2018-07-02 to 2018-06-01
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Close   20 non-null     int64
 1   Start   20 non-null     int64
 2   High    20 non-null     int64
 3   Low     20 non-null     int64
 4   Volume  20 non-null     int64
dtypes: int64(5)
memory usage: 960.0 bytes
None

In [4]:
pd.DatetimeIndex(["2022-12-25", "2023/01/25"])

DatetimeIndex(['2022-12-25', '2023-01-25'], dtype='datetime64[us]', freq=None)

In [5]:
pd.Timestamp("2023-12-25")

Timestamp('2023-12-25 00:00:00')

In [6]:
pd.to_datetime("2023년 12월 25일", format="%Y년 %m월 %d일")

Timestamp('2023-12-25 00:00:00')

In [7]:
pd.to_datetime("12-12-2023 23:59:59", format="%d-%m-%Y %H:%M:%S")

Timestamp('2023-12-12 23:59:59')

In [10]:
pd.to_datetime("2023년 12월 25일", format="%Y년 %m월 %d일")

Timestamp('2023-12-25 00:00:00')

In [11]:
pd.to_datetime("12-12-2023 23:59:59", format="%d-%m-%Y %H:%M:%S")

Timestamp('2023-12-12 23:59:59')

In [13]:
#timestamp를 이용해서 period로 변환

dates = ["2019-01-01", "2020-03-01", "2021-06-01"]

ts_dates = pd.to_datetime(dates)
ts_dates

DatetimeIndex(['2019-01-01', '2020-03-01', '2021-06-01'], dtype='datetime64[us]', freq=None)

In [14]:
pr_day = ts_dates.to_period(freq="D")
pr_day

PeriodIndex(['2019-01-01', '2020-03-01', '2021-06-01'], dtype='period[D]')

In [16]:
pr_month= ts_dates.to_period(freq="M")
pr_month

PeriodIndex(['2019-01', '2020-03', '2021-06'], dtype='period[M]')

In [17]:
pr_year = ts_dates.to_period(freq="Y")
pr_year

PeriodIndex(['2019', '2020', '2021'], dtype='period[Y-DEC]')

In [18]:
#시계열 데이터 만들기 

ts_ms = pd.date_range(start="2024-01-01",
              end=None,
              periods=6,
              freq='MS',
              tz='Asia/Seoul')

print(ts_ms)

DatetimeIndex(['2024-01-01 00:00:00+09:00', '2024-02-01 00:00:00+09:00',
               '2024-03-01 00:00:00+09:00', '2024-04-01 00:00:00+09:00',
               '2024-05-01 00:00:00+09:00', '2024-06-01 00:00:00+09:00'],
              dtype='datetime64[us, Asia/Seoul]', freq='MS')

In [19]:
ts_me = pd.date_range(start="2024-01-01",
              periods=6,
              freq='ME',
              tz='Asia/Seoul')

print(ts_me)

DatetimeIndex(['2024-01-31 00:00:00+09:00', '2024-02-29 00:00:00+09:00',
               '2024-03-31 00:00:00+09:00', '2024-04-30 00:00:00+09:00',
               '2024-05-31 00:00:00+09:00', '2024-06-30 00:00:00+09:00'],
              dtype='datetime64[us, Asia/Seoul]', freq='ME')

In [20]:
ts_3m = pd.date_range(
    "2024-01-01",
    periods=6,
    freq="3MS",
    tz="Asia/Seoul"
)

ts_3m

DatetimeIndex(['2024-01-01 00:00:00+09:00', '2024-04-01 00:00:00+09:00',
               '2024-07-01 00:00:00+09:00', '2024-10-01 00:00:00+09:00',
               '2025-01-01 00:00:00+09:00', '2025-04-01 00:00:00+09:00'],
              dtype='datetime64[us, Asia/Seoul]', freq='3MS')

In [21]:
#시계열 데이터 활용

df = pd.read_csv('./data/stock-data.csv')

df['new_Date'] = pd.to_datetime(df['Date'])
df.head()

         Date  Close  Start   High    Low  Volume   new_Date
0  2018-07-02  10100  10850  10900  10000  137977 2018-07-02
1  2018-06-29  10700  10550  10900   9990  170253 2018-06-29
2  2018-06-28  10400  10900  10950  10150  155769 2018-06-28
3  2018-06-27  10900  10800  11050  10500  133548 2018-06-27
4  2018-06-26  10800  10900  11000  10700   63039 2018-06-26

In [23]:
df['Year'] = df['new_Date'].dt.year
df['Month'] = df['new_Date'].dt.month
df['Day'] = df['new_Date'].dt.day

df.head()

         Date  Close  Start   High    Low  Volume   new_Date  Year  Month  Day
0  2018-07-02  10100  10850  10900  10000  137977 2018-07-02  2018      7    2
1  2018-06-29  10700  10550  10900   9990  170253 2018-06-29  2018      6   29
2  2018-06-28  10400  10900  10950  10150  155769 2018-06-28  2018      6   28
3  2018-06-27  10900  10800  11050  10500  133548 2018-06-27  2018      6   27
4  2018-06-26  10800  10900  11000  10700   63039 2018-06-26  2018      6   26

In [25]:
df["Date_yr"] = df["new_Date"].dt.to_period(freq="Y")

In [26]:
df["Date_M"]  = df["new_Date"].dt.to_period(freq="M")

df.head()

,Date,Close,Start,High,Low,Volume,new_Date,Year,Month,Day,Date_yr,Date_M
0,2018-07-02,10100,10850,10900,10000,137977,2018-07-02,2018,7,2,2018,2018-07
1,2018-06-29,10700,10550,10900,9990,170253,2018-06-29,2018,6,29,2018,2018-06
2,2018-06-28,10400,10900,10950,10150,155769,2018-06-28,2018,6,28,2018,2018-06
3,2018-06-27,10900,10800,11050,10500,133548,2018-06-27,2018,6,27,2018,2018-06
4,2018-06-26,10800,10900,11000,10700,63039,2018-06-26,2018,6,26,2018,2018-06

In [27]:
#시간 인덱스 활용

df = pd.read_csv("./data/stock-data.csv")
df["new_Date"] = pd.to_datetime(df["Date"])
df.head()

         Date  Close  Start   High    Low  Volume   new_Date
0  2018-07-02  10100  10850  10900  10000  137977 2018-07-02
1  2018-06-29  10700  10550  10900   9990  170253 2018-06-29
2  2018-06-28  10400  10900  10950  10150  155769 2018-06-28
3  2018-06-27  10900  10800  11050  10500  133548 2018-06-27
4  2018-06-26  10800  10900  11000  10700   63039 2018-06-26

In [28]:
df = df.set_index("new_Date")
df.head()

                  Date  Close  Start   High    Low  Volume
new_Date
2018-07-02  2018-07-02  10100  10850  10900  10000  137977
2018-06-29  2018-06-29  10700  10550  10900   9990  170253
2018-06-28  2018-06-28  10400  10900  10950  10150  155769
2018-06-27  2018-06-27  10900  10800  11050  10500  133548
2018-06-26  2018-06-26  10800  10900  11000  10700   63039

In [30]:
df = df.sort_index() # sort_values()
df.head()

                  Date  Close  Start   High    Low  Volume
new_Date
2018-06-01  2018-06-01  11900  11800  12100  11750   32062
2018-06-04  2018-06-04  11900  11900  12200  11700   25171
2018-06-05  2018-06-05  12150  11800  12250  11800   42485
2018-06-07  2018-06-07  11950  12200  12300  11900   49088
2018-06-08  2018-06-08  11950  11950  12200  11800   59258

In [31]:
df.loc["2018-06-27"]

Date      2018-06-27
Close          10900
Start          10800
High           11050
Low            10500
Volume        133548
Name: 2018-06-27 00:00:00, dtype: object

In [32]:
df.loc["2018-06-27":"2018-07-02"]

                  Date  Close  Start   High    Low  Volume
new_Date
2018-06-27  2018-06-27  10900  10800  11050  10500  133548
2018-06-28  2018-06-28  10400  10900  10950  10150  155769
2018-06-29  2018-06-29  10700  10550  10900   9990  170253
2018-07-02  2018-07-02  10100  10850  10900  10000  137977

In [33]:
cond = df.index < "2018-06-05"
cond

array([ True,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [34]:
df[cond]

                  Date  Close  Start   High    Low  Volume
new_Date
2018-06-01  2018-06-01  11900  11800  12100  11750   32062
2018-06-04  2018-06-04  11900  11900  12200  11700   25171

In [35]:
pd.Timestamp("2018-06-27")

Timestamp('2018-06-27 00:00:00')

In [36]:
pd.Timestamp(2018, 6, 27)

Timestamp('2018-06-27 00:00:00')

In [37]:
df.loc[pd.Timestamp(2018, 6, 27): pd.Timestamp(2018,7,2)]

                  Date  Close  Start   High    Low  Volume
new_Date
2018-06-27  2018-06-27  10900  10800  11050  10500  133548
2018-06-28  2018-06-28  10400  10900  10950  10150  155769
2018-06-29  2018-06-29  10700  10550  10900   9990  170253
2018-07-02  2018-07-02  10100  10850  10900  10000  137977

In [38]:
pd.Timestamp(2018, 6, 27, 10, 30 ,0)

Timestamp('2018-06-27 10:30:00')

In [39]:
df.loc[
    pd.Timestamp(2018, 6, 27, 10, 30 ,0):pd.Timestamp(2018,7,2,23,53,59)
]

                  Date  Close  Start   High    Low  Volume
new_Date
2018-06-28  2018-06-28  10400  10900  10950  10150  155769
2018-06-29  2018-06-29  10700  10550  10900   9990  170253
2018-07-02  2018-07-02  10100  10850  10900  10000  137977

In [43]:
print(pd.Timedelta("1 days"))
print(pd.Timedelta(days = 1))
print(pd.Timedelta("1 days 1 hours 1 minutes 1 seconds"))
print(pd.Timedelta(days = 1, hours= 1 , minutes=1, seconds=1))

1 days 00:00:00
1 days 00:00:00
1 days 01:01:01
1 days 01:01:01

In [44]:
pd.to_timedelta(["1 days", "3 hours"])

TimedeltaIndex(['1 days 00:00:00', '0 days 03:00:00'], dtype='timedelta64[us]', freq=None)

In [45]:
df.head()

                  Date  Close  Start   High    Low  Volume
new_Date
2018-06-01  2018-06-01  11900  11800  12100  11750   32062
2018-06-04  2018-06-04  11900  11900  12200  11700   25171
2018-06-05  2018-06-05  12150  11800  12250  11800   42485
2018-06-07  2018-06-07  11950  12200  12300  11900   49088
2018-06-08  2018-06-08  11950  11950  12200  11800   59258

In [47]:
a = df.index

In [50]:
b = pd.Timestamp("2018-07-03") - a
b

TimedeltaIndex(['32 days', '29 days', '28 days', '26 days', '25 days',
                '22 days', '21 days', '19 days', '18 days', '15 days',
                '14 days', '13 days', '12 days', '11 days',  '8 days',
                 '7 days',  '6 days',  '5 days',  '4 days',  '1 days'],
               dtype='timedelta64[us]', name='new_Date', freq=None)

In [52]:
c = a + pd.Timedelta(days=1)
c

DatetimeIndex(['2018-06-02', '2018-06-05', '2018-06-06', '2018-06-08',
               '2018-06-09', '2018-06-12', '2018-06-13', '2018-06-15',
               '2018-06-16', '2018-06-19', '2018-06-20', '2018-06-21',
               '2018-06-22', '2018-06-23', '2018-06-26', '2018-06-27',
               '2018-06-28', '2018-06-29', '2018-06-30', '2018-07-03'],
              dtype='datetime64[us]', name='new_Date', freq=None)

In [53]:
c.min()

Timestamp('2018-06-02 00:00:00')

In [54]:
c.max()

Timestamp('2018-07-03 00:00:00')