In [2]:
import pandas as pd

url = './data/sample.html'

tables = pd.read_html(url)

print(len(tables))

for i in range(len(tables)):
    print("tables[%s]" % i)
    print(tables[i])
    print(['\n'])

2
tables[0]
   Unnamed: 0  c0  c1  c2  c3
0           0   0   1   4   7
1           1   1   2   5   8
2           2   2   3   6   9
['\n']
tables[1]
         name  year        developer  opensource
0       NumPy  2006  Travis Oliphant        True
1  matplotlib  2003   John D. Hunter        True
2      pandas  2008    Wes Mckinneye        True
['\n']

In [3]:
df = tables[1]
df

         name  year        developer  opensource
0       NumPy  2006  Travis Oliphant        True
1  matplotlib  2003   John D. Hunter        True
2      pandas  2008    Wes Mckinneye        True

In [4]:
df = df.set_index(['name'])
df

            year        developer  opensource
name
NumPy       2006  Travis Oliphant        True
matplotlib  2003   John D. Hunter        True
pandas      2008    Wes Mckinneye        True