In [1]:
import pandas as pd

student1 = pd.Series({'국어':100, "영어":80, "수학":90})
print(student1)

국어    100
영어     80
수학     90
dtype: int64

In [2]:
import pandas as pd

dict_data = {
    "국어": 100,
    "영어": 80,
    "수학": 90
}

student1 = pd.Series(dict_data)
student1

국어    100
영어     80
수학     90
dtype: int64

In [3]:
percentage = student1 / 100

print(percentage)
print(type(percentage))

국어    1.0
영어    0.8
수학    0.9
dtype: float64
<class 'pandas.Series'>

In [4]:
student2 = pd.Series({"수학":80, "국어": 90, "영어":80})

print(student1)
print()
print(student2)

국어    100
영어     80
수학     90
dtype: int64

수학    80
국어    90
영어    80
dtype: int64

In [5]:
addition = student1 + student2
addition

국어    190
수학    170
영어    160
dtype: int64

In [6]:
subtraction = student1 - student2
subtraction

국어    10
수학    10
영어     0
dtype: int64

In [8]:
multiplication = student1 * student2
multiplication

국어    9000
수학    7200
영어    6400
dtype: int64

In [7]:
divison = student1 / student2
divison

국어    1.111111
수학    1.125000
영어    1.000000
dtype: float64

In [9]:
restult = pd.DataFrame([addition,subtraction,multiplication,divison],
                       index=["덧셈","뺄셈","곱셈","나눗셈"])
restult

              국어        수학      영어
덧셈    190.000000   170.000   160.0
뺄셈     10.000000    10.000     0.0
곱셈   9000.000000  7200.000  6400.0
나눗셈     1.111111     1.125     1.0

In [10]:
# NaN 값이 있는 시리즈 연산

import pandas as pd
import numpy as np

In [12]:
student1 = pd.Series({'국어':np.nan, '영어':80, "수학":90})
student2 = pd.Series({'수학':80, "국어":90})

print(student1)
print()
print(student2)

국어     NaN
영어    80.0
수학    90.0
dtype: float64

수학    80
국어    90
dtype: int64

In [14]:
addition = student1 + student2
subtraction = student1 - student2
multiplication = student1 * student2
divison = student1 / student2

print(addition)
print(subtraction)
print(multiplication)
print(divison)

국어      NaN
수학    170.0
영어      NaN
dtype: float64
국어     NaN
수학    10.0
영어     NaN
dtype: float64
국어       NaN
수학    7200.0
영어       NaN
dtype: float64
국어      NaN
수학    1.125
영어      NaN
dtype: float64

In [16]:
restult = pd.DataFrame([
    addition,
    subtraction,
    multiplication,
    divison
], index=["덧셈","뺼셈","곱셈","나눗셈"])

restult

     국어        수학  영어
덧셈  NaN   170.000 NaN
뺼셈  NaN    10.000 NaN
곱셈  NaN  7200.000 NaN
나눗셈 NaN     1.125 NaN

In [17]:
#연산 메소드
import pandas as pd
import numpy as np

student1 = pd.Series({'국어':np.nan, '영어':80, "수학":90})
student2 = pd.Series({'수학':80, "국어":90})

print(student1)
print()
print(student2)

국어     NaN
영어    80.0
수학    90.0
dtype: float64

수학    80
국어    90
dtype: int64

In [19]:
sr_add = student1.add(student2, fill_value=0)
sr_sub = student1.sub(student2, fill_value=0)
sr_mul = student1.mul(student2, fill_value=0)
sr_div = student1.div(student2, fill_value=0)

restult = pd.DataFrame([sr_add, sr_sub, sr_mul,sr_div],
                       index=["덧셈","뻴셈","곱셈","나눗셈",])

restult

       국어        수학    영어
덧셈   90.0   170.000  80.0
뻴셈  -90.0    10.000  80.0
곱셈    0.0  7200.000   0.0
나눗셈   0.0     1.125   inf

In [21]:
# 데이터 프레임 연산
#데이터프레임 vs 숫자(스칼라)

import pandas as pd
import seaborn as sns

titanic = sns.load_dataset('titanic')
df = titanic.loc[:,['age','fare']]
print(df.head())
print('\n')
print(type(df))

    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500


<class 'pandas.DataFrame'>

In [23]:
addition = df + 10
print(addition.head())
print('\n')
print(type(addition))

    age     fare
0  32.0  17.2500
1  48.0  81.2833
2  36.0  17.9250
3  45.0  63.1000
4  45.0  18.0500


<class 'pandas.DataFrame'>

In [25]:
#데이터프레임 vs 데이터프레임 

df
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [28]:
titanic = sns.load_dataset("titanic")
df = titanic.loc[:,['age','fare']]
# print(df.head())
print(df.tail())
print('\n')
print(type(df))

      age   fare
886  27.0  13.00
887  19.0  30.00
888   NaN  23.45
889  26.0  30.00
890  32.0   7.75


<class 'pandas.DataFrame'>

In [29]:
addition = df + 10
addition.head()

    age     fare
0  32.0  17.2500
1  48.0  81.2833
2  36.0  17.9250
3  45.0  63.1000
4  45.0  18.0500

In [31]:
subtraction = addition - df
subtraction.head()

    age  fare
0  10.0  10.0
1  10.0  10.0
2  10.0  10.0
3  10.0  10.0
4  10.0  10.0

In [32]:
addition.tail()

      age   fare
886  37.0  23.00
887  29.0  40.00
888   NaN  33.45
889  36.0  40.00
890  42.0  17.75

In [33]:
subtraction.tail()

      age  fare
886  10.0  10.0
887  10.0  10.0
888   NaN  10.0
889  10.0  10.0
890  10.0  10.0

In [34]:
sample1 = addition.tail()
sample1

      age   fare
886  37.0  23.00
887  29.0  40.00
888   NaN  33.45
889  36.0  40.00
890  42.0  17.75

In [39]:
sample2 = subtraction.tail().fillna(0.0)
sample2

      age  fare
886  10.0  10.0
887  10.0  10.0
888   0.0  10.0
889  10.0  10.0
890  10.0  10.0

In [40]:
sample1.add(sample2)

      age   fare
886  47.0  33.00
887  39.0  50.00
888   NaN  43.45
889  46.0  50.00
890  52.0  27.75

In [41]:
df_add = sample1.add(sample2, fill_value=0)
df_sub = sample1.sub(sample2, fill_value=0)
df_mul = sample1.mul(sample2, fill_value=0)
df_div = sample1.div(sample2, fill_value=0)

print(df_add)
print(df_sub)
print(df_mul)
print(df_div)

      age   fare
886  47.0  33.00
887  39.0  50.00
888   0.0  43.45
889  46.0  50.00
890  52.0  27.75
      age   fare
886  27.0  13.00
887  19.0  30.00
888   0.0  23.45
889  26.0  30.00
890  32.0   7.75
       age   fare
886  370.0  230.0
887  290.0  400.0
888    0.0  334.5
889  360.0  400.0
890  420.0  177.5
     age   fare
886  3.7  2.300
887  2.9  4.000
888  NaN  3.345
889  3.6  4.000
890  4.2  1.775