In [2]:
import pandas as pd
import seaborn as sns

titanic = sns.load_dataset("titanic")
df = titanic.loc[0:9,["age","fare"]]
df

    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500
5   NaN   8.4583
6  54.0  51.8625
7   2.0  21.0750
8  27.0  11.1333
9  14.0  30.0708

In [4]:
#불린 인덱싱

df["age"] < 20

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7     True
8    False
9     True
Name: age, dtype: bool

In [6]:
cond = df["age"] < 20
df[cond]

    age     fare
7   2.0  21.0750
9  14.0  30.0708

In [7]:
df.loc[cond]

    age     fare
7   2.0  21.0750
9  14.0  30.0708

In [8]:
cond = df["age"] < 20
df[~cond]

    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500
5   NaN   8.4583
6  54.0  51.8625
8  27.0  11.1333

In [11]:
#나이가 10대인 승객 을 찾습니다.

(df["age"] >= 10) & (df["age"] < 20)

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9     True
Name: age, dtype: bool

In [12]:
cond = (df["age"] >= 10) & (df["age"] < 20)
df[cond]

    age     fare
9  14.0  30.0708

In [14]:
cond = (titanic["age"] >= 10) & (titanic.age < 20)
titanic[cond]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
14,0,3,female,14.0,0,0,7.8542,S,Third,child,False,NaN,Southampton,no,True
22,1,3,female,15.0,0,0,8.0292,Q,Third,child,False,NaN,Queenstown,yes,True
27,0,1,male,19.0,3,2,263.0000,S,First,man,True,C,Southampton,no,False
38,0,3,female,18.0,2,0,18.0000,S,Third,woman,False,NaN,Southampton,no,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
853,1,1,female,16.0,0,1,39.4000,S,First,woman,False,D,Southampton,yes,False
855,1,3,female,18.0,0,1,9.3500,S,Third,woman,False,NaN,Southampton,yes,False
875,1,3,female,15.0,0,0,7.2250,C,Third,child,False,NaN,Cherbourg,yes,True
877,0,3,male,19.0,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True

In [18]:
titanic.head(2)
(titanic["age"] < 10) & (titanic["sex"] == "female")

titanic[(titanic["age"] < 10) & (titanic["sex"] == "female")]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
10,1,3,female,4.00,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
24,0,3,female,8.00,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
43,1,2,female,3.00,1,2,41.5792,C,Second,child,False,NaN,Cherbourg,yes,False
58,1,2,female,5.00,1,2,27.7500,S,Second,child,False,NaN,Southampton,yes,False
119,0,3,female,2.00,4,2,31.2750,S,Third,child,False,NaN,Southampton,no,False
147,0,3,female,9.00,2,2,34.3750,S,Third,child,False,NaN,Southampton,no,False
172,1,3,female,1.00,1,1,11.1333,S,Third,child,False,NaN,Southampton,yes,False
184,1,3,female,4.00,0,2,22.0250,S,Third,child,False,NaN,Southampton,yes,False
205,0,3,female,2.00,0,1,10.4625,S,Third,child,False,G,Southampton,no,False
233,1,3,female,5.00,4,2,31.3875,S,Third,child,False,NaN,Southampton,yes,False
237,1,2,female,8.00,0,2,26.2500,S,Second,child,False,NaN,Southampton,yes,False
297,0,1,female,2.00,1,2,151.5500,S,First,child,False,C,Southampton,no,False
374,0,3,female,3.00,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
381,1,3,female,1.00,0,2,15.7417,C,Third,child,False,NaN,Cherbourg,yes,False
448,1,3,female,5.00,2,1,19.2583,C,Third,child,False,NaN,Cherbourg,yes,False
469,1,3,female,0.75,2,1,19.2583,C,Third,child,False,NaN,Cherbourg,yes,False
479,1,3,female,2.00,0,1,12.2875,S,Third,child,False,NaN,Southampton,yes,False
530,1,2,female,2.00,1,1,26.0000,S,Second,child,False,NaN,Southampton,yes,False
535,1,2,female,7.00,0,2,26.2500,S,Second,child,False,NaN,Southampton,yes,False
541,0,3,female,9.00,4,2,31.2750,S,Third,child,False,NaN,Southampton,no,False
618,1,2,female,4.00,2,1,39.0000,S,Second,child,False,F,Southampton,yes,False
634,0,3,female,9.00,3,2,27.9000,S,Third,child,False,NaN,Southampton,no,False
642,0,3,female,2.00,3,2,27.9000,S,Third,child,False,NaN,Southampton,no,False
644,1,3,female,0.75,2,1,19.2583,C,Third,child,False,NaN,Cherbourg,yes,False
691,1,3,female,4.00,0,1,13.4167,C,Third,child,False,NaN,Cherbourg,yes,False
720,1,2,female,6.00,0,1,33.0000,S,Second,child,False,NaN,Southampton,yes,False
750,1,2,female,4.00,1,1,23.0000,S,Second,child,False,NaN,Southampton,yes,False
777,1,3,female,5.00,0,0,12.4750,S,Third,child,False,NaN,Southampton,yes,True
813,0,3,female,6.00,4,2,31.2750,S,Third,child,False,NaN,Southampton,no,False
852,0,3,female,9.00,1,1,15.2458,C,Third,child,False,NaN,Cherbourg,no,False

In [19]:
#나이가 10세 미만이고 또는 60새 이상인 승객

mask3 = (titanic.age < 10) | (titanic.age >= 60)
df_under10_morethan60 = titanic.loc[mask3,["age","sex","alone"]]
df_under10_morethan60.head()

     age     sex  alone
7    2.0    male  False
10   4.0  female  False
16   2.0    male  False
24   8.0  female  False
33  66.0    male   True

In [20]:
df["age_under_20"] = df["age"] < 20 
df

    age     fare  age_under_20
0  22.0   7.2500         False
1  38.0  71.2833         False
2  26.0   7.9250         False
3  35.0  53.1000         False
4  35.0   8.0500         False
5   NaN   8.4583         False
6  54.0  51.8625         False
7   2.0  21.0750          True
8  27.0  11.1333         False
9  14.0  30.0708          True

In [22]:
#query() 매서드 활용
# DataFrame개체.query(조건문자열)

titanic.loc[:9,["age","fare"]] 
df

    age     fare  age_under_20
0  22.0   7.2500         False
1  38.0  71.2833         False
2  26.0   7.9250         False
3  35.0  53.1000         False
4  35.0   8.0500         False
5   NaN   8.4583         False
6  54.0  51.8625         False
7   2.0  21.0750          True
8  27.0  11.1333         False
9  14.0  30.0708          True

In [23]:
df.query("age < 20")

    age     fare  age_under_20
7   2.0  21.0750          True
9  14.0  30.0708          True

In [25]:
df.query("age >= 20 and fare < 15")

    age     fare  age_under_20
0  22.0   7.2500         False
2  26.0   7.9250         False
4  35.0   8.0500         False
8  27.0  11.1333         False

In [26]:
#나이가 20세이상 또는 요금이 15만

df.query("age >= 20 or fare < 15")

    age     fare  age_under_20
0  22.0   7.2500         False
1  38.0  71.2833         False
2  26.0   7.9250         False
3  35.0  53.1000         False
4  35.0   8.0500         False
5   NaN   8.4583         False
6  54.0  51.8625         False
8  27.0  11.1333         False

In [30]:
#isin() 매서드 활용
# DataFrame객체.isin(추출값의 리스트)

pd.set_option("display.max_columns",10)
titanic

,survived,pclass,sex,age,sibsp,...,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,...,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,...,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,...,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,...,False,C,Southampton,yes,False
4,0,3,male,35.0,0,...,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,...,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,...,False,B,Southampton,yes,True
888,0,3,female,NaN,1,...,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,...,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,...,True,NaN,Queenstown,no,True

In [33]:
mask1 = titanic["embark_town"] == "Southhampton"
mask2 = titanic["embark_town"] == "Queenstown"
df_boolean = titanic[mask1 | mask2]
df_boolean

,survived,pclass,sex,age,sibsp,...,adult_male,deck,embark_town,alive,alone
5,0,3,male,NaN,0,...,True,NaN,Queenstown,no,True
16,0,3,male,2.0,4,...,False,NaN,Queenstown,no,False
22,1,3,female,15.0,0,...,False,NaN,Queenstown,yes,True
28,1,3,female,NaN,0,...,False,NaN,Queenstown,yes,True
32,1,3,female,NaN,0,...,False,NaN,Queenstown,yes,True
...,...,...,...,...,...,...,...,...,...,...,...
790,0,3,male,NaN,0,...,True,NaN,Queenstown,no,True
825,0,3,male,NaN,0,...,True,NaN,Queenstown,no,True
828,1,3,male,NaN,0,...,True,NaN,Queenstown,yes,True
885,0,3,female,39.0,0,...,False,NaN,Queenstown,no,False
890,0,3,male,32.0,0,...,True,NaN,Queenstown,no,True

In [37]:
mask3 = titanic["embark_town"].isin(["Southhampton","Queenstown"])
titanic[mask3]

,survived,pclass,sex,age,sibsp,...,adult_male,deck,embark_town,alive,alone
5,0,3,male,NaN,0,...,True,NaN,Queenstown,no,True
16,0,3,male,2.0,4,...,False,NaN,Queenstown,no,False
22,1,3,female,15.0,0,...,False,NaN,Queenstown,yes,True
28,1,3,female,NaN,0,...,False,NaN,Queenstown,yes,True
32,1,3,female,NaN,0,...,False,NaN,Queenstown,yes,True
...,...,...,...,...,...,...,...,...,...,...,...
790,0,3,male,NaN,0,...,True,NaN,Queenstown,no,True
825,0,3,male,NaN,0,...,True,NaN,Queenstown,no,True
828,1,3,male,NaN,0,...,True,NaN,Queenstown,yes,True
885,0,3,female,39.0,0,...,False,NaN,Queenstown,no,False
890,0,3,male,32.0,0,...,True,NaN,Queenstown,no,True